### ISSUE TITLE
Config from a Database table

### ISSUE THREAD

**Issue by flparedes** [grails-plugins/grails-spring-security-cas#14]
Dear all,

I'm developing a web app using Grails 3.1.9 and spring-security-cas 3.0.0.

I've followed the instructions and configured a local CAS server directly in the **application.yml** file, but now I can't figure out how I can **configure two or more environments** (local development, test, production, etc.).

My question is, how can I configure my web app, preferably with a Database table, to manage diferent environments.

Thanks in advance.

**Comment by sdelamo** [comment]
In Grails 3 you can manage different environments in `application.yml`with block such as: 

```
environments:
    development:
        ...
        ..
        .
    test:
        ...
        ..
        .
    production:
        ...
        ..
        .
```
